import { Box, Button, Image, Text, Title } from "@mantine/core";
import { ApiResponseCard } from "./ApiResponseCard";
import { Inter } from "@next/font/google";
import { IconStackPush } from "@tabler/icons";
import { Dispatch, SetStateAction } from "react";
import { useRouter } from "next/router";
import { useSupabaseClient } from "@supabase/auth-helpers-react";

const inter = Inter({ subsets: ["latin"] });

export const AutoGeneratedBox = ({
  setUserInputText,
  creatingFollowing,
  followingStory,
}: {
  setUserInputText: Dispatch<SetStateAction<string | null>>;
  creatingFollowing: boolean;
  followingStory: string | null;
}) => {
  const router = useRouter();
  const supabaseClient = useSupabaseClient();

  const saveDraft = async (userInput: string) => {
    const id = router.query.id;

    try {
      await supabaseClient
        .from("drafts")
        .update({
          content: userInput,
        })
        .eq("id", id);
    } catch (err) {}
  };

  const pushText = (additionalText: string) => {
    setUserInputText((prev) => {
      if (prev === null || prev === "") {
        return additionalText;
      }
      const implodedText = `${prev}\n${additionalText}`;

      saveDraft(implodedText);

      return implodedText;
    });
  };

  return (
    <Box>
      <Title order={3} mb={30} className={inter.className}>
        The autocomplete by Penelope
      </Title>
      {!followingStory && !creatingFollowing && (
        <Image
          alt=""
          w="50%"
          mx="auto"
          src="https://hjulmtlogrkrcmkvcqmk.supabase.co/storage/v1/object/public/public-images/waiting-penelope"
          sx={{
            maxWidth: 200,
          }}
        />
      )}
      {creatingFollowing && <Text ta="center">Penelope is thinking...</Text>}
      {!creatingFollowing && followingStory && (
        <Box mb={15}>
          <ApiResponseCard result={followingStory} />
          <Button
            leftIcon={<IconStackPush />}
            onClick={() => pushText(followingStory)}
            radius="xl"
            size="sm"
            fullWidth
            mt={10}
            color="dark"
          >
            Add it to the end of your document
          </Button>
        </Box>
      )}
    </Box>
  );
};
