import { Box, Image, Title } from "@mantine/core";
import { ApiResponseCard } from "./ApiResponseCard";
import { ApiResponsePlaceholder } from "./ApiResponsePlaceholder";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const AutoGeneratedBox = ({
  creatingFollowing,
  followingStory,
}: {
  creatingFollowing: boolean;
  followingStory: string | null;
}) => {
  return (
    <Box>
      <Title order={3} mb={30} className={inter.className}>
        Auto generated next sentence by Penelope
      </Title>
      {!followingStory && !creatingFollowing && (
        <Image
          alt=""
          w="50%"
          mx="auto"
          src="https://hjulmtlogrkrcmkvcqmk.supabase.co/storage/v1/object/public/public-images/waiting-penelope"
          sx={{
            maxWidth: 200,
          }}
        />
      )}
      {creatingFollowing && <ApiResponsePlaceholder />}
      {!creatingFollowing && followingStory && (
        <Box mb={15}>
          <ApiResponseCard result={followingStory} />
        </Box>
      )}
    </Box>
  );
};
